
/**
* factHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fact.idl
* Wednesday, March 11, 2020 10:45:04 AM CET
*/

public final class factHolder implements org.omg.CORBA.portable.Streamable
{
  public fact value = null;

  public factHolder ()
  {
  }

  public factHolder (fact initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = factHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    factHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return factHelper.type ();
  }

}
