
/**
* factPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fact.idl
* Wednesday, March 11, 2020 10:45:04 AM CET
*/

public abstract class factPOA extends org.omg.PortableServer.Servant
 implements factOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calculfact", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // fact/calculfact
       {
         int n = in.read_long ();
         double $result = (double)0;
         $result = this.calculfact (n);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:fact:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public fact _this() 
  {
    return factHelper.narrow(
    super._this_object());
  }

  public fact _this(org.omg.CORBA.ORB orb) 
  {
    return factHelper.narrow(
    super._this_object(orb));
  }


} // class factPOA
