
/**
* hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, March 11, 2020 10:06:53 AM CET
*/

public interface hello extends helloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface hello
