
/**
* FactHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fact.idl
* Wednesday, March 11, 2020 1:46:28 PM CET
*/

public final class FactHolder implements org.omg.CORBA.portable.Streamable
{
  public Fact value = null;

  public FactHolder ()
  {
  }

  public FactHolder (Fact initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FactHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FactHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FactHelper.type ();
  }

}
