
/**
* Fact_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fact.idl
* Wednesday, March 11, 2020 1:46:28 PM CET
*/

public class Fact_Tie extends _FactImplBase
{

  // Constructors
  public Fact_Tie ()
  {
  }

  public Fact_Tie (FactOperations impl)
  {
    super ();
    _impl = impl;
  }

  public long factoriel (int N)
  {
    return _impl.factoriel(N);
  } // factoriel

  private FactOperations _impl;

} // class Fact_Tie
