
/**
* FactOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fact.idl
* Wednesday, March 11, 2020 1:46:28 PM CET
*/

public interface FactOperations 
{
 long factoriel (int N);
} // interface FactOperations
