
/**
* FactHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fact.idl
* Wednesday, March 11, 2020 1:46:28 PM CET
*/

abstract public class FactHelper
{
  private static String  _id = "IDL:Fact:1.0";

  public static void insert (org.omg.CORBA.Any a, Fact that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Fact extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FactHelper.id (), "Fact");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Fact read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FactStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Fact value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Fact narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fact)
      return (Fact)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FactStub stub = new _FactStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Fact unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Fact)
      return (Fact)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FactStub stub = new _FactStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
