
/**
* hello_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, March 11, 2020 1:03:20 PM CET
*/

public class hello_Tie extends _helloImplBase
{

  // Constructors
  public hello_Tie ()
  {
  }

  public hello_Tie (helloOperations impl)
  {
    super ();
    _impl = impl;
  }

  public String sayhello ()
  {
    return _impl.sayhello();
  } // sayhello

  private helloOperations _impl;

} // class hello_Tie
