
/**
* helloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, March 11, 2020 1:03:20 PM CET
*/

public final class helloHolder implements org.omg.CORBA.portable.Streamable
{
  public hello value = null;

  public helloHolder ()
  {
  }

  public helloHolder (hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = helloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    helloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return helloHelper.type ();
  }

}
