
/**
* helloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, March 11, 2020 1:03:20 PM CET
*/

public interface helloOperations 
{
  String sayhello ();
} // interface helloOperations